export const TRAINER_LOGIN_REQUEST = "TRAINER_LOGIN_REQUEST";
export const TRAINER_LOGIN_SUCCESS = "TRAINER_LOGIN_SUCCESS";
export const TRAINER_LOGIN_FAIL = "TRAINER_LOGIN_FAIL";
export const TRAINER_LOGOUT = "TRAINER_LOGOUT";

export const TRAINER_REGISTER_REQUEST = "TRAINER_REGISTER_REQUEST";
export const TRAINER_REGISTER_SUCCESS = "TRAINER_REGISTER_SUCCESS";
export const TRAINER_REGISTER_FAIL = "TRAINER_REGISTER_FAIL";

export const TRAINER_UPDATE_REQUEST = "TRAINER_UPDATE_REQUEST";
export const TRAINER_UPDATE_SUCCESS = "TRAINER_UPDATE_SUCCESS";
export const TRAINER_UPDATE_FAIL = "TRAINER_UPDATE_FAIL";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_UPDATE_REQUEST = "TRAINER_UPDATE_REQUEST";
export const ADMIN_UPDATE_SUCCESS = "TRAINER_UPDATE_SUCCESS";
export const ADMIN_UPDATE_FAIL = "TRAINER_UPDATE_FAIL";
